### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CobraOI** [Joshj5hawk/JoshJ5Hawk-SuperAmmo#2]
just wanted to ask if youll be adding .338 Lapua Magnum ammo and also in the future once you've completed super ammos would you consider adding like super mags with like 100 ergo and low feed ect.

**Comment by Snowblind808** [comment]
He already added super .338 Lapua, its just called something different in game, but visually looks the same as .338 Lapua AP, so you just have to look for it, and he added compatibility with the Olympus mod, which had super magazines with very high capacity and such if your looking for that.

**Comment by CobraOI** [comment]
fair enough ill take a look thanks for the info

**Comment by Joshj5hawk** [comment]
Yepp, the Relover Ammo *is* there, but I have to do some extra tweaking to get it to work properly. Gonna take a stab at it in the next day or so!

**Comment by CobraOI** [comment]
no worries mate loving the mod so far keep it up!
